"""AXI data-node COVERAGE-GAP suite — the tests the B-node work never wrote.

Companion to `test_axi_datanode_recovery.py` (Fix G / Fix H / I5). That suite
proves the WRITE-RESPONSE (B) node end to end. This one closes the two holes a
2026-08-02 verification review of the eth-chiplet silicon pushback found in it:

  GAP-1  FOUR OF THE FIVE AXI FC NODES HAVE NO ERROR-INJECTION TEST AT ALL.
         Every existing test injects on data_id 0x82 (B). AW (0x80), W (0x81),
         AR (0x83) and R (0x84) are untested in sim AND on silicon, yet the
         consumer's stated acceptance gate is "errinject per node in
         {AW,W,B,AR,R} x several bits, expect recovery on every one"
         (nanosoc-ethernet-chiplet docs/HANDOVER_AXI_DATANODE_RECOVERY.md).
         The READ path matters most: one of the two originally-reported silicon
         wedge points was a peer READ, and the read return path (AR out, R back)
         has a DIFFERENT backstop than writes — `sub_rd_os_r` is a single BIT,
         not the saturating counter Fix H gave writes.

  GAP-2  THE I5 BACKSTOP'S OWN SEMANTICS ARE UNVERIFIED. I5 is only ever
         observed doing the thing it was built for (fire once, on one stuck
         write, on an otherwise idle link). Four properties it must also hold
         are asserted here for the first time:
           a) the AHB ERROR it emits is a LEGAL AHB-Lite response — i.e. it
              lands in the data phase of a transfer the master is actually
              waiting on, not on an idle bus. I5 is deliberately
              HREADYOUT-BLIND and tracks POSTED (bufferable, HPROT[2]=1)
              writes the master has already retired, so "ERROR into an idle
              bus" is reachable BY CONSTRUCTION -- and an upstream bridge is
              entitled to ignore such a pulse. That is a candidate mechanism
              for the on-silicon "HRESP=ERROR is driven but never reaches the
              PS" (docs/ila_capA_i5_fires_2026_08_02.csv).
           b) a stuck response is still timed out while OTHER traffic is
              progressing. `sub_axi_progress = sub_r_done | sub_b_done` resets
              the ONE shared age counter for ALL outstanding transactions, so
              any completing beat on either channel re-arms the timer for a
              transaction that is genuinely stuck. The on-silicon repro that
              wedged used a 32-beat resume STREAM; the only case ever proven
              in sim or on the ILA is `--stream 0` (a single beat, nothing else
              in flight).
           c) the backstop RESTORES the path. Firing an AHB ERROR upstream does
              not by itself unwedge XHB500: the ILA shows `xhb_sub_hreadyout_raw`
              still 0 and `sub_ext_stalled` re-arming immediately after the
              ERROR (samples 258+). If the window path is dead after one lost
              response, "bounded to HRESP=ERROR" is not the same as "recovered".
           d) it RE-ARMS. On expiry the RTL zeroes `sub_wr_os_ctr`/`sub_rd_os_r`
              to abandon the timed-out transaction, but the abandoned response
              may still arrive later and decrement/clear the tracking of a
              LATER transaction, leaving a second lost response untimed.

Runtime notes (inherited from the companion suite):
  * every test needs its OWN sim — a left-armed Force corrupts the next bring-up
  * built against the SHORT I5 timeout (2^13) so the backstop tests finish;
    `make gaps_*` targets pass +define+TIDELINK_SUB_OUTSTANDING_TIMEOUT_LOG2=13
  * the node-coverage tests (GAP-1) do NOT need the short timeout.
"""
import os
import cocotb
from cocotb.triggers import RisingEdge, ClockCycles
from cocotb.handle import Force, Release

from pair_v2_common import PairV2TB, run_bringup_full

# ── the five AXI FC nodes ────────────────────────────────────────────────────
# data_id: WlinkGenericFCSM{,_1,_2,_3,_4}.v swi_data_id_1 reset defaults.
# tx_side: which die TRANSMITS that packet type for a die-m-initiated access
#          (m issues AW/W/AR; s returns B/R). Inject on the transmitter.
# The NACK is generated by the RECEIVER, i.e. the other die's same-named node.
NODES = {
    "AW": dict(data_id=0x80, inst="wlink_axiawFC", tx_side="m", op="write"),
    "W":  dict(data_id=0x81, inst="wlink_axiwFC",  tx_side="m", op="write"),
    "B":  dict(data_id=0x82, inst="wlink_axibFC",  tx_side="s", op="write"),
    "AR": dict(data_id=0x83, inst="wlink_axiarFC", tx_side="m", op="read"),
    "R":  dict(data_id=0x84, inst="wlink_axirFC",  tx_side="s", op="read"),
}
AXI_FC_NODES = [n["inst"] for n in NODES.values()]

APER_BASE  = 0x4000_0000
OFF_SANITY = 0x100
OFF_INJECT = 0x200
OFF_RD     = 0x300
OFF_POST   = 0x400
D_SANITY   = 0xC0FFEE01
D_INJECT   = 0xBEEF1234
D_RD       = 0x5EED0042
D_POST     = 0xA5A50FF0
REG_OBS_AXI_NODES = 0x21E0

BYTE_PKTNUM = 4    # header pktnum -> isNotExpPacket (detected with CRC on OR off)
# Byte 0 is the packet's `data_id`. The CRC comparison is GATED on
# `data_id === swi_data_id` (FC.scala:157, documented in
# cocotb/tidelink_error_injection/test_ei_crc_probe.py:34-40), so corrupting it
# makes the packet not-a-data-packet: it is silently DROPPED at the receiver, no
# CRC error is raised, no NACK is sent, and nothing is ever replayed. This is
# the "clean silent drop" the on-silicon ILA capture used
# (docs/AXI_DATANODE_RECOVERY_AMPLIFIER_SOUND_2026_08_01.md:232, byte 0 +
# --stream 0) — the failure mode Fix G's NACK/replay is structurally blind to.
BYTE_DATA_ID = 0


# ── hierarchy / force helpers (kept local: importing a module that defines
#    @cocotb.test() risks pulling its tests into this regression) ────────────
def _axi_node(tb, side, inst):
    return getattr(tb.top(side).u_chiplet_controller.u_wlink.axi2wl, inst)


def _wlink(tb, side):
    return tb.top(side).u_chiplet_controller.u_wlink


def _sig(node, name):
    try:    return int(getattr(node, name).value)
    except Exception: return None


def _slave_bram_peek(dut, off):
    try:    return int(dut.u_s_mng_bram.mem[off >> 2].value)
    except Exception: return None


def _force_axi_crc(tb, on):
    for side in ("m", "s"):
        for inst in AXI_FC_NODES:
            try:    _axi_node(tb, side, inst).out_prepend_swi_disable_crc.value = \
                        (Force(0) if on else Release())
            except Exception: pass


def _force_fix_off(tb, off):
    """Force socl_l7_reached_link_data=0 on every AXI node = the PRE-Fix-G RTL
    (bring-up forgive stays armed forever, so a detected error never NACKs)."""
    n = 0
    for side in ("m", "s"):
        for inst in AXI_FC_NODES:
            try:
                _axi_node(tb, side, inst).socl_l7_reached_link_data.value = \
                    (Force(0) if off else Release())
                n += 1
            except Exception: pass
    return n


async def _arm_injector(tb, side, data_id, byte, bit=0):
    """One-shot Wlink built-in injector (the 0x2E03_003C silicon model)."""
    wl = _wlink(tb, side)
    wl.swi_err_inj_data_id.value = Force(data_id)
    wl.out_prepend_swi_err_inj_byte.value = Force(byte)
    wl.out_prepend_swi_err_inj_bit.value = Force(bit)
    wl.out_prepend_swi_err_inj.value = Force(0)
    await ClockCycles(tb.dut.hclk, 4)
    wl.out_prepend_swi_err_inj.value = Force(1)
    await ClockCycles(tb.dut.hclk, 4)


async def _arm_injector_persistent(tb, side, data_id, byte, bit=0):
    """PERSISTENT injection: hold err_inj_smack high so every matching SOP —
    including every NACK-driven REPLAY — is re-corrupted, i.e. the response can
    never converge. Models a permanently-lost response."""
    wl = _wlink(tb, side)
    wl.swi_err_inj_data_id.value = Force(data_id)
    wl.out_prepend_swi_err_inj_byte.value = Force(byte)
    wl.out_prepend_swi_err_inj_bit.value = Force(bit)
    wl.lltx.err_inj_smack.value = Force(1)
    await ClockCycles(tb.dut.hclk, 4)


def _disarm_injector(tb, side):
    wl = _wlink(tb, side)
    for a in ("swi_err_inj_data_id", "out_prepend_swi_err_inj_byte",
              "out_prepend_swi_err_inj_bit", "out_prepend_swi_err_inj"):
        try:    getattr(wl, a).value = Release()
        except Exception: pass
    try:    wl.lltx.err_inj_smack.value = Release()
    except Exception: pass


def _release_all(tb):
    for side in ("m", "s"):
        _disarm_injector(tb, side)
        for inst in AXI_FC_NODES:
            node = _axi_node(tb, side, inst)
            for a in ("out_prepend_swi_disable_crc", "socl_l7_reached_link_data"):
                try:    getattr(node, a).value = Release()
                except Exception: pass


async def _region_f(tb):
    try:    raw = await tb.apb("m").read(REG_OBS_AXI_NODES)
    except Exception: return (None, None, None)
    return ((raw >> 23) & 1, ((raw >> 12) & 1) | ((raw >> 17) & 1), raw)


# ── AHB-Lite master on m_ahb_sub_* ───────────────────────────────────────────
class AHBSubMaster:
    """Single-beat AHB-Lite master. TimeoutError = response never returned;
    RuntimeError = HRESP=ERROR (a backstop fired); clean return = completed.

    Adds, over the companion suite's copy, an `activity` trace: for every clock
    it records whether the master had a transfer OUTSTANDING (address accepted,
    data phase not yet complete). `test_i5_error_is_ahb_legal` uses it to decide
    whether an ERROR pulse landed on a real transfer or on an idle bus."""

    def __init__(self, dut):
        self.dut = dut; self.clk = dut.hclk
        self.hsel = dut.m_ahb_sub_hsel; self.haddr = dut.m_ahb_sub_haddr
        self.hburst = dut.m_ahb_sub_hburst; self.hprot = dut.m_ahb_sub_hprot
        self.hsize = dut.m_ahb_sub_hsize; self.htrans = dut.m_ahb_sub_htrans
        self.hwdata = dut.m_ahb_sub_hwdata; self.hwrite = dut.m_ahb_sub_hwrite
        self.hready = dut.m_ahb_sub_hready; self.hrdata = dut.m_ahb_sub_hrdata
        self.hresp = dut.m_ahb_sub_hresp; self.hreadyout = dut.m_ahb_sub_hreadyout
        self.outstanding = False       # a transfer is in its data phase
        self.idle()

    def idle(self):
        self.hsel.value = 0; self.haddr.value = 0; self.hburst.value = 0
        self.hprot.value = 0; self.hsize.value = 2; self.htrans.value = 0
        self.hwdata.value = 0; self.hwrite.value = 0; self.hready.value = 1
        self.outstanding = False

    def _resp(self):
        try:    return int(self.hresp.value)
        except ValueError: return 0

    def _rdata(self):
        try:    return int(self.hrdata.value)
        except ValueError: return -1

    async def _run(self, addr, write, wdata, timeout):
        await RisingEdge(self.clk)
        self.hsel.value = 1; self.haddr.value = addr & 0xFFFF_FFFF
        self.htrans.value = 2; self.hsize.value = 2; self.hburst.value = 0
        self.hprot.value = 0; self.hwrite.value = 1 if write else 0
        self.hready.value = 1
        if write: self.hwdata.value = wdata & 0xFFFF_FFFF
        await RisingEdge(self.clk)
        self.hsel.value = 0; self.htrans.value = 0; self.hwrite.value = 0
        self.hburst.value = 0
        self.outstanding = True
        seen_low = False; rdata, resp, done = -1, 0, False
        for _ in range(timeout):
            await RisingEdge(self.clk)
            r = int(self.hreadyout.value)
            if not r: seen_low = True
            elif seen_low:
                rdata = self._rdata(); resp = self._resp(); done = True; break
        self.idle()
        op = "WRITE" if write else "READ"
        if not done: raise TimeoutError(f"ahb_sub {op} 0x{addr:08x} WEDGE")
        if resp:     raise RuntimeError(f"ahb_sub {op} 0x{addr:08x} HRESP=ERROR")
        return rdata

    async def write(self, addr, data, timeout=80000):
        await self._run(addr, True, data, timeout)

    async def read(self, addr, timeout=80000):
        return await self._run(addr, False, 0, timeout)

    async def write_bufferable(self, addr, data, node, timeout=80000):
        """Bufferable single write (HPROT[2]=1 -> XHB500 early-write-response).
        The master is RELEASED as soon as the bridge posts it, so after this
        returns the AHB bus is IDLE while the write is still outstanding on
        s_axi. Completion is detected by this write's AW being accepted.
        `node` is the tidelink_top instance (dut.u_master), which is where the
        XHB500 s_axi handshakes are visible."""
        await RisingEdge(self.clk)
        self.hsel.value = 1; self.haddr.value = addr & 0xFFFF_FFFF
        self.htrans.value = 2; self.hsize.value = 2; self.hburst.value = 0
        self.hprot.value = 0x4; self.hwrite.value = 1; self.hready.value = 1
        self.hwdata.value = data & 0xFFFF_FFFF
        await RisingEdge(self.clk)
        self.hsel.value = 0; self.htrans.value = 0; self.hwrite.value = 0
        self.outstanding = True
        accepted = False
        for _ in range(timeout):
            await RisingEdge(self.clk)
            try:
                if int(node.s_axi_awvalid.value) and int(node.s_axi_awready.value):
                    accepted = True; break
            except ValueError: pass
            if int(self.hreadyout.value) and self._resp():
                self.idle(); raise RuntimeError(f"ahb_sub bufW 0x{addr:08x} HRESP=ERROR")
        if accepted:
            await ClockCycles(self.clk, 4)
        self.idle()
        if not accepted: raise TimeoutError(f"ahb_sub bufW 0x{addr:08x} STALL")
        return True


async def _err_watch(dut, master, out, cycles):
    """Sample the master-facing AHB response every cycle. Records each HRESP=1
    pulse together with whether the master had a transfer outstanding at the
    time — the AHB-Lite legality question. Also tracks the DUT-internal
    backstop registers so 'no ERROR at all' can be told apart from 'ERROR fired
    but invisible at the port'."""
    prev = 0
    out.setdefault("pulses", [])
    out.setdefault("err1_fires", 0)
    out.setdefault("osr_max", 0)
    prev_e1 = 0
    for _ in range(cycles):
        await RisingEdge(dut.hclk)
        try:
            e1 = int(dut.u_master.sub_err1_r.value)
            if e1 and not prev_e1: out["err1_fires"] += 1
            prev_e1 = e1
            c = int(dut.u_master.sub_osr_ctr_r.value)
            if c > out["osr_max"]: out["osr_max"] = c
        except Exception: pass
        try:    resp = int(dut.m_ahb_sub_hresp.value)
        except ValueError: continue
        if resp and not prev:
            out["pulses"].append({
                "outstanding": master.outstanding,
                "hreadyout": int(dut.m_ahb_sub_hreadyout.value),
            })
        prev = resp


# =============================================================================
# GAP-1 — per-node error-injection coverage (the consumer's acceptance gate)
# =============================================================================
async def _bringup(dut, crc_on=True, fix_off=False):
    tb = PairV2TB(dut)
    master = AHBSubMaster(dut)
    await run_bringup_full(tb)
    assert await tb.wait_cr_crack(), "no CR/CRACK"
    await ClockCycles(dut.hclk, 200)
    _force_axi_crc(tb, crc_on)
    _force_fix_off(tb, fix_off)
    await master.write(APER_BASE + OFF_SANITY, D_SANITY)
    await ClockCycles(dut.hclk, 2000)
    assert _slave_bram_peek(dut, OFF_SANITY) == D_SANITY, "clean sanity write failed"
    return tb, master


async def _run_node_scenario(dut, name, crc_on=True, fix_off=False):
    """Bring up, inject ONE single-bit error on `name`'s packet stream, drive
    the transaction that carries it, and classify RECOVER / WEDGE / ERROR."""
    n = NODES[name]
    tb, master = await _bringup(dut, crc_on=crc_on, fix_off=fix_off)
    rx_side = "s" if n["tx_side"] == "m" else "m"
    rx_node = _axi_node(tb, rx_side, n["inst"])
    dut._log.info(f"[gaps] node={name} id=0x{n['data_id']:02x} tx={n['tx_side']} "
                  f"rx={rx_side} op={n['op']} CRC={'on' if crc_on else 'off'} "
                  f"FixG={'OFF(forced)' if fix_off else 'on'}")

    if n["op"] == "read":
        # Seed the far-side terminus through the proven WRITE path, and prove
        # the clean read works BEFORE injecting (else a read failure could be
        # a broken read path rather than the injected error).
        await master.write(APER_BASE + OFF_RD, D_RD)
        await ClockCycles(dut.hclk, 2000)
        pre = await master.read(APER_BASE + OFF_RD)
        assert pre == D_RD, f"clean peer READ broken before inject: 0x{pre:08x}"

    seen = {"state7": False, "nack_req": False, "crc0": _sig(rx_node, "crc_errors")}

    async def mon(cycles):
        for _ in range(cycles):
            await RisingEdge(dut.hclk)
            if _sig(rx_node, "state") == 7: seen["state7"] = True
            if _sig(rx_node, "send_nack_req"): seen["nack_req"] = True

    m = cocotb.start_soon(mon(80000))
    await _arm_injector(tb, n["tx_side"], n["data_id"], BYTE_PKTNUM)

    out = {"node": name, "class": None, "value_ok": None}
    try:
        if n["op"] == "read":
            got = await master.read(APER_BASE + OFF_RD, timeout=80000)
            out["class"] = "RECOVER"; out["value_ok"] = (got == D_RD); out["got"] = got
        else:
            await master.write(APER_BASE + OFF_INJECT, D_INJECT, timeout=80000)
            out["class"] = "RECOVER"
            await ClockCycles(dut.hclk, 2000)
            out["value_ok"] = (_slave_bram_peek(dut, OFF_INJECT) == D_INJECT)
    except TimeoutError: out["class"] = "WEDGE"
    except RuntimeError: out["class"] = "ERROR"

    await ClockCycles(dut.hclk, 500)
    m.kill()
    out["nack_fired"] = seen["state7"] or seen["nack_req"]
    out["crc_errs_rose"] = (_sig(rx_node, "crc_errors") or 0) > (seen["crc0"] or 0)
    dh, sticky, _ = await _region_f(tb)
    out["data_healthy"] = dh; out["wedge_sticky"] = sticky
    dut._log.info(f"[gaps] OUTCOME {out}")
    _release_all(tb)
    await ClockCycles(dut.hclk, 50)
    return out


def _assert_recovered(o):
    assert o["class"] == "RECOVER", f"node {o['node']}: did not recover (class={o['class']})"
    assert o["value_ok"] is True,   f"node {o['node']}: recovered but NOT byte-exact ({o})"
    assert o["nack_fired"] is True, f"node {o['node']}: recovered without a NACK — vacuous"


@cocotb.test()
async def test_axi_r_error_recovers(dut):
    """GAP-1 / R (0x84) — READ-DATA return path. The mirror of the proven B
    test and the highest-value hole: a peer READ was one of the two originally
    reported silicon wedge points, and reads are backstopped by a single BIT
    (`sub_rd_os_r`), not Fix H's saturating counter."""
    _assert_recovered(await _run_node_scenario(dut, "R"))


@cocotb.test()
async def test_axi_r_error_wedges_no_fix(dut):
    """GAP-1 / R non-vacuity: with Fix G forced OFF the same injected R error
    must NOT cleanly recover. If this passes-as-recovered, the R test above is
    proving nothing (the error never mattered)."""
    o = await _run_node_scenario(dut, "R", fix_off=True)
    assert not (o["class"] == "RECOVER" and o["value_ok"]), (
        f"VACUOUS: R error recovered byte-exact with Fix G disabled ({o})")


@cocotb.test()
async def test_axi_ar_error_recovers(dut):
    """GAP-1 / AR (0x83) — read REQUEST path."""
    _assert_recovered(await _run_node_scenario(dut, "AR"))


@cocotb.test()
async def test_axi_aw_error_recovers(dut):
    """GAP-1 / AW (0x80) — write ADDRESS path."""
    _assert_recovered(await _run_node_scenario(dut, "AW"))


@cocotb.test()
async def test_axi_w_error_recovers(dut):
    """GAP-1 / W (0x81) — write DATA path."""
    _assert_recovered(await _run_node_scenario(dut, "W"))


# =============================================================================
# GAP-2 — I5 backstop semantics
# =============================================================================
@cocotb.test()
async def test_i5_error_is_ahb_legal(dut):
    """GAP-2a — the ERROR I5 emits must be a LEGAL AHB-Lite response.

    Scenario: a POSTED (bufferable) write whose B is permanently corrupted.
    XHB500's early-write-response releases the AHB master immediately, so the
    bus is IDLE while the write is still outstanding on s_axi — exactly the
    case I5 exists for (the per-beat stall timer is blind to it because
    HREADYOUT is high). When I5 expires it drives HRESP=1 for two cycles.

    AHB-Lite: a subordinate may only signal ERROR during the DATA PHASE of a
    transfer it was selected for. If HRESP=1 is asserted with no transfer
    outstanding, an upstream bridge is entitled to discard it — which would
    explain the silicon observation that I5 drove HRESP=ERROR and the PS never
    saw a bus error (docs/ila_capA_i5_fires_2026_08_02.csv).

    FAIL here = a real defect: `ahb_sub_hresp`/`ahb_sub_hreadyout` are driven
    from `sub_err{1,2}_r` alone (tidelink_top.sv ~:1703-1710), with NO
    qualification that a transfer is in its data phase."""
    tb, master = await _bringup(dut)
    trace = {}
    w = cocotb.start_soon(_err_watch(dut, master, trace, 60000))

    await _arm_injector_persistent(tb, "s", NODES["B"]["data_id"], BYTE_PKTNUM)
    try:
        await master.write_bufferable(APER_BASE + OFF_POST, D_POST,
                                      dut.u_master, timeout=20000)
    except (TimeoutError, RuntimeError) as e:
        dut._log.info(f"[gaps] posted write did not post cleanly: {e}")

    # Master is now idle; wait past the (short-build) I5 timeout.
    await ClockCycles(dut.hclk, 40000)
    w.kill()
    _release_all(tb)
    dut._log.info(f"[gaps] err1_fires={trace['err1_fires']} osr_max={trace['osr_max']} "
                  f"HRESP pulses={trace['pulses']}")

    assert trace["err1_fires"] > 0, (
        f"NO BACKSTOP AT ALL — I5 never fired on a posted write with a "
        f"permanently-lost B (osr_max={trace['osr_max']}). That is an unbounded "
        f"hang, which is worse than an illegal error.")
    assert trace["pulses"], (
        "sub_err1_r fired but NO HRESP=1 ever reached the ahb_sub port")
    illegal = [p for p in trace["pulses"] if not p["outstanding"]]
    assert not illegal, (
        f"AHB-ILLEGAL ERROR: {len(illegal)}/{len(trace['pulses'])} HRESP=1 pulses "
        f"were driven with NO transfer in its data phase ({illegal}). An upstream "
        f"AHB->AXI bridge may legitimately discard these, so the PS never sees a "
        f"bus error and hangs — the on-silicon symptom.")


@cocotb.test()
async def test_i5_traffic_behind_a_stuck_write_is_bounded(dut):
    """GAP-2b — traffic issued BEHIND a stuck posted write must be bounded.

    ORIGINAL HYPOTHESIS (2026-08-02), now REFUTED — kept because the negative
    result is the useful part. `sub_axi_progress = sub_r_done | sub_b_done`
    resets the ONE shared `sub_osr_ctr_r` for ALL outstanding transactions, so
    in principle any completing beat on EITHER channel re-arms the age timer of
    a transaction that is genuinely stuck — the same defect class Fix H fixed
    one level down. The route to it looked open: a posted (bufferable) write
    releases the AHB master, which is then free to issue reads that complete
    normally while the write's B is permanently lost.

    MEASURED: the route is CLOSED. XHB500 serialises the sub port — with a
    posted write's B outstanding the bridge does not complete a following read,
    so no concurrent progress can be generated and the masking condition cannot
    be created from this port. (First run, 6000-cycle read timeout: read WEDGE,
    err1_fires=0. Second run, 12000-cycle timeout — longer than the 2^13 I5
    window: read returns HRESP=ERROR, err1_fires=1, osr_max=8192, and the pulse
    is `outstanding: True`, i.e. a LEGAL error, because the read master IS
    held.) So `sub_osr_ctr_r` being shared is a latent smell, not a reachable
    defect on the ahb_sub port.

    WHAT THIS NOW ASSERTS (a real property, and the useful regression): a
    transaction issued behind a stuck posted write is terminated by a bounded,
    AHB-LEGAL error rather than hanging. If a future change lets the sub port
    pipeline across channels, the shared-counter hazard reopens and the
    `outstanding` check here is what will catch it."""
    tb, master = await _bringup(dut)
    await master.write(APER_BASE + OFF_RD, D_RD)
    await ClockCycles(dut.hclk, 2000)

    trace = {}
    w = cocotb.start_soon(_err_watch(dut, master, trace, 120000))

    await _arm_injector_persistent(tb, "s", NODES["B"]["data_id"], BYTE_PKTNUM)
    try:
        await master.write_bufferable(APER_BASE + OFF_POST, D_POST,
                                      dut.u_master, timeout=20000)
    except (TimeoutError, RuntimeError) as e:
        dut._log.info(f"[gaps] posted write: {e}")

    # Keep the OTHER channel progressing. Each completed read pulses
    # sub_r_done -> sub_axi_progress -> sub_osr_ctr_r <= 0.
    reads_ok, blocked = 0, None
    for i in range(24):
        try:
            # Timeout must exceed the I5 window (2^13 in the gaps build) or a
            # read that is merely SLOW is misread as blocked.
            got = await master.read(APER_BASE + OFF_RD, timeout=12000)
            if got == D_RD: reads_ok += 1
        except RuntimeError as e:
            blocked = "ERROR"; dut._log.info(f"[gaps] read {i} bounded: {e}"); break
        except TimeoutError as e:
            blocked = "HANG";  dut._log.info(f"[gaps] read {i} hung: {e}"); break
        await ClockCycles(dut.hclk, 200)
    w.kill()
    _release_all(tb)
    dut._log.info(f"[gaps] reads_ok={reads_ok} blocked={blocked} "
                  f"err1_fires={trace['err1_fires']} osr_max={trace['osr_max']} "
                  f"HRESP pulses={trace['pulses']}")

    # Either XHB500 serialises (the measured behaviour: the following read is
    # bounded by a legal ERROR) or it pipelines (reads complete -> the shared
    # counter is being reset -> the stuck write MUST still be timed out).
    if blocked == "ERROR":
        assert trace["err1_fires"] > 0, "read errored but no backstop fired"
        illegal = [p for p in trace["pulses"] if not p["outstanding"]]
        assert not illegal, (
            f"the bounding ERROR was AHB-illegal (no transfer in its data "
            f"phase): {illegal} — see F-1 / test_i5_error_is_ahb_legal")
    else:
        assert blocked != "HANG", (
            "UNBOUNDED: a read issued behind a stuck posted write hung with no "
            "backstop — neither serialised nor timed out.")
        assert trace["err1_fires"] > 0, (
            f"PROGRESS MASKING: {reads_ok} reads completed while a posted "
            f"write's B was permanently lost, and the backstop NEVER fired. The "
            f"single shared age counter (sub_axi_progress = sub_r_done | "
            f"sub_b_done) is reset by unrelated traffic, so a stuck transaction "
            f"is never timed out and the PS hangs unbounded.")


@cocotb.test()
async def test_i5_backstop_restores_the_path(dut):
    """GAP-2c — after the backstop fires, the window path must WORK again.

    Firing an AHB ERROR upstream abandons the transfer at the tidelink wrapper,
    but does nothing to XHB500's own FSM or to the FC node. The silicon ILA
    shows `xhb_sub_hrdyout_raw` still 0 and `sub_ext_stalled` re-arming
    immediately after the ERROR (samples 258+), i.e. the bridge is still
    wedged. If a subsequent CLEAN transaction cannot complete, the backstop is
    an error REPORT, not a recovery — and every later PS access costs another
    full timeout (~2.6 ms at 25 MHz), which presents to a host as a hang."""
    tb, master = await _bringup(dut)

    await _arm_injector_persistent(tb, "s", NODES["B"]["data_id"], BYTE_PKTNUM)
    fired = False
    try:
        await master.write(APER_BASE + OFF_INJECT, D_INJECT, timeout=60000)
    except RuntimeError:  fired = True          # HRESP=ERROR — backstop tripped
    except TimeoutError:  pass
    assert fired, "backstop never fired — cannot test post-backstop recovery"

    # Remove the fault entirely, give the link time to settle, then retry clean.
    _disarm_injector(tb, "s")
    await ClockCycles(dut.hclk, 20000)

    try:
        await master.write(APER_BASE + OFF_POST, D_POST, timeout=60000)
        await ClockCycles(dut.hclk, 2000)
        landed = _slave_bram_peek(dut, OFF_POST)
    except (TimeoutError, RuntimeError) as e:
        _release_all(tb)
        raise AssertionError(
            f"PATH DEAD AFTER BACKSTOP: with the fault REMOVED, the next clean "
            f"write still failed ({e}). The backstop reports an error but never "
            f"restores XHB500/the FC node, so the window is permanently dead "
            f"after one lost response.")
    _release_all(tb)
    assert landed == D_POST, (
        f"post-backstop write completed but landed 0x{landed:08x} != 0x{D_POST:08x}")


@cocotb.test()
async def test_i5_clean_drop_leaves_path_usable(dut):
    """GAP-2c (silicon-faithful variant) — the CAPTURED silicon wedge, in sim.

    `test_i5_backstop_restores_the_path` uses a REMOVABLE fault: once the
    injector is disarmed the pending NACK/replay converges, XHB500 finally gets
    its B, and the bridge unblocks. The on-silicon capture is a different and
    strictly harder case: a byte-0 (`data_id`) corruption is a CLEAN SILENT
    DROP — no CRC check (the comparison is gated on data_id), no NACK, no
    replay. The response is gone forever, so XHB500 waits for a beat that can
    never arrive, and disarming the injector changes nothing.

    Silicon ground truth (docs/ila_capA_i5_fires_2026_08_02.csv, byte 0,
    --stream 0): for ALL 3839 samples after the backstop ERROR,
    `dbg_xhb_hrdyout_raw` is 0 — never once high — `dbg_i5_ext_stalled` is 1,
    and `dbg_i5_stall_ctr` is ramping again toward the next 2^16 expiry. The
    wrapper's ERROR abandoned the transfer upstream but did NOT unwedge the
    bridge, so the window path is permanently dead and every later PS access
    costs another full timeout.

    This test asserts the property that ground truth denies: after a
    silently-dropped response is backstopped, a subsequent CLEAN access still
    works."""
    tb, master = await _bringup(dut)

    await _arm_injector(tb, "s", NODES["B"]["data_id"], BYTE_DATA_ID)
    fired, cls = False, None
    try:
        await master.write(APER_BASE + OFF_INJECT, D_INJECT, timeout=60000)
        cls = "RECOVER"
    except RuntimeError: cls = "ERROR"; fired = True
    except TimeoutError: cls = "WEDGE"
    dut._log.info(f"[gaps] clean-drop write: {cls}")
    _disarm_injector(tb, "s")
    await ClockCycles(dut.hclk, 20000)

    assert cls != "RECOVER", (
        "byte-0 (data_id) corruption RECOVERED — unexpected: it should be an "
        "undetectable silent drop. Re-check the injector byte mapping.")
    assert fired, f"silently-dropped B was not backstopped at all (class={cls})"

    try:
        await master.write(APER_BASE + OFF_POST, D_POST, timeout=60000)
        await ClockCycles(dut.hclk, 2000)
        landed = _slave_bram_peek(dut, OFF_POST)
    except (TimeoutError, RuntimeError) as e:
        _release_all(tb)
        raise AssertionError(
            f"PATH DEAD AFTER A SILENTLY-DROPPED RESPONSE: the next CLEAN write "
            f"failed ({e}) even though the fault is gone. Matches the silicon "
            f"ILA (xhb_hrdyout_raw never returns high). The backstop reports an "
            f"error but cannot restore XHB500 — one lost response kills the "
            f"window path permanently.")
    _release_all(tb)
    assert landed == D_POST, (
        f"post-drop write completed but landed 0x{landed:08x} != 0x{D_POST:08x}")


@cocotb.test()
async def test_i5_rearms_after_abort(dut):
    """GAP-2d — a SECOND lost response after an abort must also be timed out.

    On expiry the RTL zeroes `sub_wr_os_ctr`/`sub_rd_os_r` to abandon the
    timed-out transaction (tidelink_top.sv ~:1651-1652). The abandoned response
    may still arrive afterwards; with the tracker already at zero it is either
    ignored or, worse, decrements the accounting of a LATER transaction — after
    which a second genuinely-lost response is never timed out and the PS hangs
    with no backstop at all."""
    tb, master = await _bringup(dut)

    async def trip(tag):
        await _arm_injector_persistent(tb, "s", NODES["B"]["data_id"], BYTE_PKTNUM)
        got = None
        try:
            await master.write(APER_BASE + OFF_INJECT, D_INJECT, timeout=60000)
            got = "RECOVER"
        except RuntimeError: got = "ERROR"
        except TimeoutError: got = "WEDGE"
        dut._log.info(f"[gaps] trip {tag}: {got}")
        _disarm_injector(tb, "s")
        await ClockCycles(dut.hclk, 20000)
        return got

    first  = await trip("1st")
    assert first == "ERROR", f"1st lost response was not backstopped ({first})"
    second = await trip("2nd")
    _release_all(tb)
    assert second == "ERROR", (
        f"BACKSTOP DID NOT RE-ARM: the 2nd permanently-lost response gave "
        f"'{second}', not a bounded HRESP=ERROR. After one abort the outstanding "
        f"tracker no longer bounds a stuck transaction.")
