#-----------------------------------------------------------------------------
# TideLink — partition-level SDC overlay (multi-clock + CDC).
#
# The shared FC.read_design.tcl already creates the main system clock
# ($CLK_NAME = hclk @ $CLK_PERIOD = 4 ns) and applies all_inputs/
# all_outputs I/O delays. This file adds the additional clock domains
# the partition exposes at its boundary, and declares them as async
# groups so synthesis/STA don't time CDC paths between them.
#
# Read into every active scenario by 1_init_design.tcl.
#
# Rationale per clock:
#   phc_clk       — PTP RTC reference, generated separately on chip-top.
#                   Crosses into hclk via tidelink_phc_cdc; the bridge
#                   does the actual CDC, STA must not time the raw
#                   register-to-register paths.
#   scan_clk      — DFT scan clock; only active in test mode.
#   user_ref_clk  — Wlink internal/user reference; provided by SoC PLL.
#   pad_clk_rx    — Recovered from the peer chiplet's pad_clk_tx; fully
#                   asynchronous to anything generated locally.
#
# NOTE: SDC syntax — fc_shell's read_sdc parser does NOT accept the
# `-quiet` flag on get_ports / get_clocks (CMD-010). Every clock + port
# pattern referenced here is part of tidelink_top's fixed boundary, so
# unconditional commands are safe; conditional blocks use catch / sizeof
# without -quiet.
#-----------------------------------------------------------------------------

# ── Secondary clock domains ──────────────────────────────────────────────
# Provisional 50 MHz / 20 ns. Pin to the actual RTC frequency once the
# top-level chip clocking plan is settled.
create_clock -name phc_clk -period 20.0 -waveform {0 10} [get_ports phc_clk]

# Conservative 100 MHz / 10 ns; tester pace, not functional path.
create_clock -name scan_clk -period 10.0 -waveform {0 5} [get_ports scan_clk]

# Provisional 250 MHz / 4 ns (matches the 4 ns hclk default; placeholder
# until the chip-top clocking plan firms up).
create_clock -name user_ref_clk -period 4.0 -waveform {0 2} [get_ports user_ref_clk]

# Wlink RX pad clock (recovered from peer). Async to everything local.
create_clock -name pad_clk_rx -period 4.0 -waveform {0 2} [get_ports pad_clk_rx]

# ── Async clock groups ────────────────────────────────────────────────────
# All five clocks are physically asynchronous — separate sources, no
# common reference. CDC is enforced in RTL by tidelink_phc_cdc and the
# Wlink internal synchronisers. STA must not time paths between groups.
set_clock_groups -asynchronous \
    -group {hclk}         \
    -group {phc_clk}      \
    -group {scan_clk}     \
    -group {user_ref_clk} \
    -group {pad_clk_rx}

# ── Boundary I/O delays for the new clock domains ─────────────────────────
# 25% of each clock period. The SDC parser does not accept sizeof_collection
# or -quiet, so these are applied unconditionally — all referenced ports
# are part of tidelink_top's fixed boundary.

# phc_clk-domain output (phc_hw_capture is the partition's PHC handoff
# back to the SoC's PHC block). Inputs phc_seconds/phc_nanoseconds/
# phc_pps come IN through tidelink_phc_cdc and are false-pathed by the
# clock-group declaration above.
set_output_delay -clock phc_clk [expr 20.0 * 0.25] [get_ports phc_hw_capture] -add_delay

# pad_clk_rx-domain inputs (Wlink RX lanes sample on the recovered clock).
set_input_delay -clock pad_clk_rx [expr 4.0 * 0.25] [get_ports pad_rx*] -add_delay

# pad_clk_tx is generated by the partition (Wlink TX router) — tools will
# infer it from internal clock divisions. No create_clock here.
