#-----------------------------------------------------------------------------
# TideLink — partition-level SDC overlay (multi-clock + CDC).
#
# The shared FC.read_design.tcl already creates the main system clock
# ($CLK_NAME = hclk @ $CLK_PERIOD = 4 ns) and applies all_inputs/
# all_outputs I/O delays. This file adds the additional clock domains
# the partition exposes at its boundary, and declares them as async
# groups so synthesis/STA don't time CDC paths between them.
#
# Read into every active scenario by 1_init_design.tcl.
#
# Rationale per clock:
#   phc_clk       — PTP RTC reference, generated separately on chip-top.
#                   Crosses into hclk via tidelink_phc_cdc; the bridge
#                   does the actual CDC, STA must not time the raw
#                   register-to-register paths.
#   scan_clk      — DFT scan clock; only active in test mode.
#   user_ref_clk  — Wlink internal/user reference; provided by SoC PLL.
#   pad_clk_rx    — Recovered from the peer chiplet's pad_clk_tx; fully
#                   asynchronous to anything generated locally.
#-----------------------------------------------------------------------------

# ── PHC / PTP RTC reference ───────────────────────────────────────────────
# Provisional 50 MHz / 20 ns. Pin to the actual RTC frequency once the
# top-level chip clocking plan is settled.
if {[sizeof_collection [get_ports phc_clk -quiet]] > 0} {
    create_clock -name phc_clk -period 20.0 -waveform {0 10} \
        [get_ports phc_clk]
}

# ── DFT scan clock ────────────────────────────────────────────────────────
# Conservative 100 MHz / 10 ns; tester pace, not functional path.
if {[sizeof_collection [get_ports scan_clk -quiet]] > 0} {
    create_clock -name scan_clk -period 10.0 -waveform {0 5} \
        [get_ports scan_clk]
}

# ── Wlink user reference clock ────────────────────────────────────────────
# Provisional 250 MHz / 4 ns (matches the 4 ns hclk default; placeholder
# until the chip-top clocking plan firms up).
if {[sizeof_collection [get_ports user_ref_clk -quiet]] > 0} {
    create_clock -name user_ref_clk -period 4.0 -waveform {0 2} \
        [get_ports user_ref_clk]
}

# ── Wlink RX pad clock (recovered from peer chiplet) ──────────────────────
# Async to every locally-generated clock; placeholder period mirrors the
# Wlink default.
if {[sizeof_collection [get_ports pad_clk_rx -quiet]] > 0} {
    create_clock -name pad_clk_rx -period 4.0 -waveform {0 2} \
        [get_ports pad_clk_rx]
}

# ── Async clock groups ────────────────────────────────────────────────────
# All five clocks are physically asynchronous — separate sources, no
# common reference. CDC is enforced in RTL by tidelink_phc_cdc and the
# Wlink internal synchronisers. STA must not time paths between groups.
set _async_groups [list]
foreach clk {hclk phc_clk scan_clk user_ref_clk pad_clk_rx} {
    if {[sizeof_collection [get_clocks -quiet $clk]] > 0} {
        lappend _async_groups -group $clk
    }
}
if {[llength $_async_groups] >= 4} {
    eval set_clock_groups -asynchronous $_async_groups
}

# ── Boundary I/O delays for the new clock domains ─────────────────────────
# 25% of each clock period, matching the convention the shared FC
# read_design.tcl applies to hclk.

# phc_clk-domain ports (PTP block exposes RTC time fields)
if {[sizeof_collection [get_clocks -quiet phc_clk]] > 0} {
    set phc_io_delay [expr 20.0 * 0.25]
    set phc_outs [get_ports -quiet {ptp_*}]
    if {[sizeof_collection $phc_outs] > 0} {
        set_output_delay -clock phc_clk $phc_io_delay $phc_outs -add_delay
    }
}

# pad_clk_rx-domain inputs (Wlink RX lanes sample on the recovered clock)
if {[sizeof_collection [get_clocks -quiet pad_clk_rx]] > 0} {
    set pad_io_delay [expr 4.0 * 0.25]
    set rx_pads [get_ports -quiet {pad_rx*}]
    if {[sizeof_collection $rx_pads] > 0} {
        set_input_delay -clock pad_clk_rx $pad_io_delay $rx_pads -add_delay
    }
}

# pad_clk_tx is generated by the partition (Wlink TX router) — tools will
# infer it from internal clock divisions. No create_clock here.
