#-----------------------------------------------------------------------------
# TideLink Chiplet Bridge - Pynq-Z2 Single-Instance Timing Constraints (Wave B1)
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access license.
#
# Contributors
#
# David Mapstone (d.a.mapstone@soton.ac.uk)
#
# Copyright (C) 2026, SoC Labs (www.soclabs.org)
#-----------------------------------------------------------------------------
# Timing constraints for implementation only. Applying these during synthesis
# fires CRITICAL WARNING 12-4739 ("No valid object(s) found") because the
# clk_wiz output clocks are not visible to the synthesis engine.
#
# Applied via build_design.tcl:
#   set_property USED_IN_SYNTHESIS false [get_files *_timing.xdc]
#-----------------------------------------------------------------------------
set_property USED_IN_SYNTHESIS false [get_files [file normalize [info script]]]

#-----------------------------------------------------------------------------
# GPIO PHY pad clocks
#
# The TideLink PHY runs at 50 MHz (source-synchronous: the TX clock is
# forwarded with the data; the RX clock is received from the remote node).
# These clocks are not generated by the MMCM — they come from the PHY pads.
#
# Create virtual clocks for source-synchronous analysis:
#   - tl_tx_clk: 50 MHz, forwarded by TideLink on pad_clk_tx
#   - tl_rx_clk: 50 MHz, received on pad_clk_rx from the remote node
#
# The clk_wiz 50 MHz HCLK output (clk_out1) is the system clock; its
# generated clock is automatically defined by the clk_wiz IP. No
# create_generated_clock call is needed here for hclk.
#-----------------------------------------------------------------------------

# Virtual TX clock — source-synchronous reference for pad_clk_tx and pad_tx[*].
# This tells Vivado that pad_clk_tx is launched from the 50 MHz domain.
create_clock -name tl_tx_clk -period 20.0 [get_ports pad_clk_tx]

# Virtual RX clock — received from the remote chiplet on pad_clk_rx.
# Used as the capture clock for pad_rx[*].
create_clock -name tl_rx_clk -period 20.0 [get_ports pad_clk_rx]

#-----------------------------------------------------------------------------
# GPIO PHY pad I/O timing (conservative, 50 MHz)
#
# Budget: 5 ns out of a 20 ns period, leaving 15 ns for board trace + setup.
# Tighten once board trace lengths are measured.
#
# pad_tx[*] are output relative to pad_clk_tx (source-synchronous DDR later;
# for first bring-up SDR is sufficient).
# pad_rx[*] are input relative to pad_clk_rx from the remote node.
#-----------------------------------------------------------------------------

# Output delays on TX data lanes relative to TX clock
set_output_delay -clock [get_clocks tl_tx_clk] -min -5.0 [get_ports {pad_tx[*]}]
set_output_delay -clock [get_clocks tl_tx_clk] -max  5.0 [get_ports {pad_tx[*]}]

# Input delays on RX data lanes relative to RX clock
set_input_delay  -clock [get_clocks tl_rx_clk] -min -5.0 [get_ports {pad_rx[*]}]
set_input_delay  -clock [get_clocks tl_rx_clk] -max  5.0 [get_ports {pad_rx[*]}]

# The forwarded TX clock itself has no setup/hold budget — it is the
# reference clock for the TX domain. Mark it as false-path for timing
# (the MMCM output is the real timing reference; pad_clk_tx is a pure
# clock forward pin with no data timing to analyse at this stage).
set_false_path -to [get_ports pad_clk_tx]

#-----------------------------------------------------------------------------
# Clock domain crossings
#
# The clk_wiz produces two phase-aligned 50 MHz outputs from the same MMCM
# (clk_out1 = hclk, clk_out2 = phc_clk). These are synchronous by
# construction — no CDC path exists between them. Declare this to prevent
# Vivado flagging false CDC warnings across the two outputs.
#-----------------------------------------------------------------------------
# (No set_false_path needed — Vivado automatically treats synchronous outputs
#  of the same MMCM as related clocks. The clk_wiz IP defines this.)

#-----------------------------------------------------------------------------
# False paths
#-----------------------------------------------------------------------------

# LEDs are human-visible; no functional timing path needed.
set_false_path -to [get_ports {led0 led1 led2 led3}]

# pad_clk_rx: incoming clock from remote node — treated as an external clock
# source, not an output to be timed from the MMCM perspective.
# (Already handled by create_clock above; no additional false_path needed.)

#-----------------------------------------------------------------------------
# Combinational loop waivers
#-----------------------------------------------------------------------------

# The IP wrapper hard-wires HSEL=1 and loops HREADYOUT back to HREADY_IN on
# the AHB slaves (ahblite:2.0 sub-signal pattern). This is the standard
# Vivado IP-Integrator AHB-Lite slave style and creates a combinational
# loop on the HREADY net inside the IP. The loop is intentional and
# functionally correct for an always-selected, single-master AHB slave.
# Downgrade LUTLP-1 (combinatorial loop) from ERROR to WARNING for the
# IP-Integrator AHB-Lite HSEL=1 + HREADY loopback pattern. The loop is
# intentional. Resolving via per-net ALLOW_COMBINATORIAL_LOOPS would need
# knowing the auto-generated net hierarchy, which changes between Vivado
# versions; the global severity downgrade is more robust and only relaxes
# this specific DRC.
set_property SEVERITY {Warning} [get_drc_checks LUTLP-1]
