###-----------------------------------------------------------------------------
### TideLink Chiplet Bridge - Pynq-Z2 - DRC waivers
### A joint work commissioned on behalf of SoC Labs, under Arm Academic Access license.
###-----------------------------------------------------------------------------
### Sole purpose: contain DRC severity overrides + ALLOW_COMBINATORIAL_LOOPS
### waivers in a SEPARATE XDC file so they survive `save_constraints` round-trips
### (which rewrites *_timing.xdc and tends to drop these properties).
###
### Applied during BOTH synthesis and implementation (default).
###-----------------------------------------------------------------------------

# IP-Integrator AHB-Lite HSEL=1 + HREADY loopback creates an intentional
# combinatorial loop on the HREADY net. Downgrade the DRC severity globally
# AND apply per-net waiver — write_bitstream's pre-DRC has historically
# ignored the severity downgrade in Vivado 2024.1.
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -hierarchical -filter {NAME =~ "*u_xhb_sub/u_core/u_resp/*"}]
# Debug core stanzas stripped — insert_debug_core.tcl will recreate them
# (the dbg_int + dbg_hub stanzas previously here connected to mark_debug nets
# in WlinkRxLinkLayer.v; those nets were disabled by Agent M (feat/remove-mark-debug)
# so the probes had no valid endpoints — synthesis pruned the source nets and
# impl failed with Chipscope 16-213 unconnected channels. Without mark_debug
# there is no need for the auto-debug-core, so the entire stanza is dropped.
# If a future fold reinstates mark_debug attrs OR adds an explicit ILA, this
# stanza needs to be regenerated by Vivado save_constraints after running
# fpga/scripts/insert_debug_core.tcl with FPGA_INSERT_DEBUG_CORE=1.)






