###-----------------------------------------------------------------------------
### TideLink Chiplet Subsystem - Vivado Build Driver Script
### A joint work commissioned on behalf of SoC Labs, under Arm Academic Access license.
###
### Contributors
###
### David Mapstone (d.a.mapstone@soton.ac.uk)
###
### Copyright (C) 2026, SoC Labs (www.soclabs.org)
###-----------------------------------------------------------------------------
### Top-level Vivado TCL driver: creates project, sources block design,
### adds wrapper and constraints, runs synth/impl/bitstream and exports
### bitstream + .hwh for PYNQ overlay loading.
###
### Required environment variables:
###   FPGA_PART        - Xilinx part number (e.g. xc7z020clg400-1)
###   FPGA_PROJECT_DIR - Output directory for Vivado project
###   FPGA_IP_REPO     - Path to packaged IP repository
###   FPGA_TARGET_DIR  - Path to target-specific files (BD TCL, wrapper, XDC)
###   FPGA_OUTPUT_DIR  - Path for final outputs (.bit, .hwh, .xsa)
###   FPGA_NUM_JOBS    - Number of parallel jobs for synthesis/implementation
###-----------------------------------------------------------------------------

set part        $env(FPGA_PART)
set project_dir $env(FPGA_PROJECT_DIR)
set ip_repo     $env(FPGA_IP_REPO)
set target_dir  $env(FPGA_TARGET_DIR)
set output_dir  $env(FPGA_OUTPUT_DIR)

if { [info exists env(FPGA_NUM_JOBS)] } {
    set num_jobs $env(FPGA_NUM_JOBS)
} else {
    set num_jobs 4
}

puts "==========================================="
puts " TideLink Chiplet Subsystem FPGA Build"
puts " Part:    $part"
puts " Project: $project_dir"
puts " IP Repo: $ip_repo"
puts " Target:  $target_dir"
puts " Output:  $output_dir"
puts " Jobs:    $num_jobs"
puts "==========================================="

# STEP 1: Create Vivado project
create_project tidelink_project $project_dir -part $part -force

# STEP 2: Add IP repository
set_property ip_repo_paths $ip_repo [current_project]
update_ip_catalog

# STEP 3: Source block design
source $target_dir/tidelink_design.tcl

set design_name tidelink_design
create_bd_design $design_name
create_root_design ""

# STEP 4: Add board-level wrapper
add_files $target_dir/tidelink_design_wrapper.v
set_property top tidelink_design_wrapper [current_fileset]

# STEP 5: Add constraints
# Pin assignment XDC — used in synthesis and implementation
set pin_xdc [lindex [glob -nocomplain $target_dir/*_tidelink.xdc] 0]
if { $pin_xdc ne "" } {
    add_files -fileset constrs_1 $pin_xdc
} else {
    puts "WARNING: no pin XDC found at $target_dir/*_tidelink.xdc"
}

# Timing XDC — implementation only (set_property USED_IN_SYNTHESIS false)
set timing_xdc [lindex [glob -nocomplain $target_dir/*_tidelink_timing.xdc] 0]
if { $timing_xdc ne "" } {
    add_files -fileset constrs_1 $timing_xdc
    set_property USED_IN_SYNTHESIS false \
        [get_files $timing_xdc]
    set_property USED_IN_IMPLEMENTATION true \
        [get_files $timing_xdc]
} else {
    puts "WARNING: no timing XDC found at $target_dir/*_tidelink_timing.xdc"
}

# DRC waiver XDC — separate file so save_constraints (which rewrites the
# timing XDC during debug-core insertion) can't strip our SEVERITY +
# ALLOW_COMBINATORIAL_LOOPS overrides. Applied during impl only (the
# combinatorial loop is post-route DRC).
set drc_xdc [lindex [glob -nocomplain $target_dir/*_tidelink_drc.xdc] 0]
if { $drc_xdc ne "" } {
    add_files -fileset constrs_1 $drc_xdc
    set_property USED_IN_SYNTHESIS false \
        [get_files $drc_xdc]
    set_property USED_IN_IMPLEMENTATION true \
        [get_files $drc_xdc]
}

# IDELAY XDC — SoC Labs §9 structural fix. Separate file (NOT *_timing.xdc,
# which another agent owns). Carries the IODELAY_GROUP binding for the
# per-lane IDELAYE2 + IDELAYCTRL and the IOB-policy for pad_rx[*]. Applied
# in BOTH synth and impl so the IODELAY_GROUP string attribute on the cells
# is honoured by the placer/router. No-op (empty get_cells) on a
# USE_IDELAY=0 build, so adding it unconditionally is safe.
set idelay_xdc [lindex [glob -nocomplain $target_dir/*_tidelink_idelay.xdc] 0]
if { $idelay_xdc ne "" } {
    add_files -fileset constrs_1 $idelay_xdc
    set_property USED_IN_SYNTHESIS true \
        [get_files $idelay_xdc]
    set_property USED_IN_IMPLEMENTATION true \
        [get_files $idelay_xdc]
}

# STEP 6: Generate block design outputs
# Be specific about WHICH BD - using *.bd matches nested SmartConnect
# sub-designs which can only be generated by their parent.
generate_target all [get_files ${design_name}.bd]

# STEP 7: Update compile order
update_compile_order -fileset sources_1

# STEP 7.5: Verilog defines.
# FPGA_DEBUG_ILA gates Xilinx-specific `(* mark_debug = "true" *)` attrs in
# the chiplet RTL (deps/axi-chiplet-controller/logical/top/, .../i2c/rtl/).
# Without it the attributes evaluate to nothing, so ASIC synthesis tools
# (Design Compiler / Fusion Compiler / Genus) never see the vendor-specific
# attribute. Defining it here keeps the marks live for Vivado's
# insert_debug_core flow (controlled separately by FPGA_INSERT_DEBUG_CORE).
#
# 2026-05-21: TEMPORARILY DISABLED — when defined, Vivado infers ila_rx on
# the pad_clk_rx domain (per mark_debug attrs on autoneg / I2C signals).
# That ILA introduces a hold-timing violation
# (WHS = -596 ps on tidelink_design_i/ila_rx/inst/PROBE_PIPE.shift_probes_reg[0][0]/D
#  with source pad_clk_rx) which corrupts the recovered-clock domain's
# flops -> all lanes fail to lock (0/16 on bridge1).
# Re-enable once: (a) the ILA probe taps are moved off pad_clk_rx, OR
# (b) hold-fix constraints are applied around the ILA probe pipe.
# See docs/V2_DEFERRALS.md (new Bug #4 entry).
# set_property verilog_define {FPGA_DEBUG_ILA=1} [current_fileset]

# STEP 8: Synthesis
puts "Starting synthesis..."
launch_runs synth_1 -jobs $num_jobs
wait_on_run synth_1

set synth_status [get_property STATUS [get_runs synth_1]]
puts "Synthesis status: $synth_status"
if { [string match "*ERROR*" $synth_status] } {
    puts "ERROR: Synthesis failed!"
    exit 1
}

# STEP 8.5: Insert ILA debug core for nets marked (* mark_debug = "true" *).
# Skipped silently if no marks present.
if { [info exists env(FPGA_INSERT_DEBUG_CORE)] && $env(FPGA_INSERT_DEBUG_CORE) == "1" } {
    set debug_tcl [file join [file dirname [info script]] insert_debug_core.tcl]
    if { [file exists $debug_tcl] } {
        puts "Inserting debug core via $debug_tcl..."
        source $debug_tcl
    }
}

# STEP 9: Implementation + Bitstream
puts "Starting implementation..."
launch_runs impl_1 -to_step write_bitstream -jobs $num_jobs
wait_on_run impl_1

set impl_status [get_property STATUS [get_runs impl_1]]
puts "Implementation status: $impl_status"
if { [string match "*ERROR*" $impl_status] } {
    puts "ERROR: Implementation failed!"
    exit 1
}

# STEP 10: Export outputs (.bit, .hwh for PYNQ, .xsa for Vitis)
file mkdir $output_dir

set bit_file [glob -nocomplain $project_dir/tidelink_project.runs/impl_1/*.bit]
if { $bit_file ne "" } {
    file copy -force $bit_file $output_dir/tidelink.bit
    puts "Bitstream copied to $output_dir/tidelink.bit"
}

# .hwh is required for PYNQ - it's the IP-XACT flat hardware description.
# Look for it in the BD's hw_handoff directory.
set hwh_file [glob -nocomplain $project_dir/tidelink_project.gen/sources_1/bd/$design_name/hw_handoff/${design_name}.hwh]
if { $hwh_file eq "" } {
    # Fallback path used by older Vivado versions
    set hwh_file [glob -nocomplain $project_dir/tidelink_project.srcs/sources_1/bd/$design_name/hw_handoff/${design_name}.hwh]
}
if { $hwh_file ne "" } {
    file copy -force $hwh_file $output_dir/tidelink.hwh
    puts ".hwh copied to $output_dir/tidelink.hwh"
} else {
    puts "WARNING: .hwh file not found - PYNQ overlay loading will fail"
}

# Export hardware platform (.xsa) - useful for Vitis and as a self-contained
# bundle (the .xsa is just a zip containing .bit + .hwh + metadata).
write_hw_platform -fixed -include_bit -force $output_dir/tidelink_design.xsa

puts "==========================================="
puts " Build complete!"
puts " Bitstream: $output_dir/tidelink.bit"
puts " HWH:       $output_dir/tidelink.hwh"
puts " XSA:       $output_dir/tidelink_design.xsa"
puts "==========================================="

close_project
