#!/usr/bin/env bash
#-----------------------------------------------------------------------------
# Calibre LVS wrapper for the TideLink partition.
#
# Usage: run_calibre_lvs.sh <deck> <gds> <netlist> <top> <work> <reports> <logs> <runsets>
#
# Generates a small TVF wrapper at <runsets>/lvs.tvf that INCLUDEs the
# foundry deck and overrides LAYOUT / SOURCE / LVS REPORT / MASK SVDB
# AFTER the include (SVRF last-wins). Then runs `calibre -lvs -hier -64`
# against the wrapper. Source for LVS = the gate-level Verilog netlist;
# Calibre's v2lvs flow extracts a SPICE source from the .v.
#
# Note: previous revision emitted Calibre Workbench runset files
# (*lvsRulesFile: ... format) — that format is only read by the
# calibrewb GUI, not by command-line `calibre -lvs`. The wrapper TVF
# pattern below is the documented batch-mode invocation.
#-----------------------------------------------------------------------------
set -euo pipefail

deck="$1"
gds="$2"
netlist="$3"
top="$4"
work="$5"
reports="$6"
logs="$7"
runsets="$8"

mkdir -p "$work" "$reports" "$logs" "$runsets"

wrapper="$runsets/lvs.tvf"
report="$work/${top}_lvs.rep"
svdb_dir="$work/svdb"
log="$logs/calibre_lvs.log"

# Emit a small TVF wrapper. INCLUDE the foundry deck FIRST so our
# LAYOUT / SOURCE / LVS REPORT / MASK SVDB lines come after and win.
cat > "$wrapper" <<EOF
// TideLink LVS wrapper — auto-generated by run_calibre_lvs.sh
// Includes the TSMC65 LVS deck and overrides layout / source /
// report targets to point at the partition GDS + .v this build
// produced.

INCLUDE "${deck}"

LAYOUT PATH "${gds}"
LAYOUT PRIMARY "${top}"
LAYOUT SYSTEM GDSII

SOURCE PATH "${netlist}"
SOURCE PRIMARY "${top}"
SOURCE SYSTEM VERILOG

MASK SVDB DIRECTORY "${svdb_dir}" QUERY
LVS REPORT "${report}"
LVS REPORT OPTION S
EOF

echo "INFO: [calibre_lvs] wrapper → $wrapper"
echo "INFO: [calibre_lvs] deck    = $deck"
echo "INFO: [calibre_lvs] layout  = $gds"
echo "INFO: [calibre_lvs] source  = $netlist"
echo "INFO: [calibre_lvs] top     = $top"

cd "$work"
set +e
/eda/mentor/calibre/bin/calibre -lvs -hier -64 "$wrapper" 2>&1 | tee "$log"
rc=${PIPESTATUS[0]}
set -e

# Calibre LVS writes a "Comparison Results" section to $report — grep
# the canonical pass / fail signature into the summary.
{
    echo "================================================================="
    echo " Calibre LVS summary — ${top}"
    echo " deck    : ${deck}"
    echo " layout  : ${gds}"
    echo " source  : ${netlist}"
    echo " wrapper : ${wrapper}"
    echo " report  : ${report}"
    echo " log     : ${log}"
    echo " calibre exit: $rc"
    echo "================================================================="
    if [ -f "$report" ]; then
        echo ""
        echo " --- Comparison Results ---"
        sed -n '/COMPARISON RESULTS/,/^[[:space:]]*$/p' "$report" | head -40 || true
        echo ""
        if grep -q "CORRECT" "$report" 2>/dev/null; then
            echo " RESULT: LVS CORRECT (extracted source ↔ layout match)"
        elif grep -q "INCORRECT" "$report" 2>/dev/null; then
            echo " RESULT: LVS INCORRECT — see $report"
        else
            echo " RESULT: indeterminate — Calibre may not have completed comparison"
        fi
    else
        echo " (no LVS .rep produced — Calibre may not have run a compare pass)"
    fi
    echo "================================================================="
} > "$reports/10_calibre_lvs.rep"

cat "$reports/10_calibre_lvs.rep"

if [ $rc -ne 0 ]; then
    echo "ERROR: Calibre LVS exited non-zero ($rc) — see $log"
    exit $rc
fi
echo "CALIBRE_LVS_OK: $top"
